var annotated_dup =
[
    [ "err_fail_to_read_func_txt", "classerr__fail__to__read__func__txt.html", null ],
    [ "err_fail_to_read_iter_txt", "classerr__fail__to__read__iter__txt.html", null ],
    [ "err_fail_to_read_results_txt", "classerr__fail__to__read__results__txt.html", null ],
    [ "err_invalid_fifth_line", "classerr__invalid__fifth__line.html", null ],
    [ "err_invalid_first_line", "classerr__invalid__first__line.html", null ],
    [ "err_invalid_fourth_line", "classerr__invalid__fourth__line.html", null ],
    [ "err_invalid_initial_point", "classerr__invalid__initial__point.html", null ],
    [ "err_invalid_lhs_poly", "classerr__invalid__lhs__poly.html", null ],
    [ "err_invalid_max_iter", "classerr__invalid__max__iter.html", null ],
    [ "err_invalid_rhs_poly", "classerr__invalid__rhs__poly.html", null ],
    [ "err_invalid_third_line", "classerr__invalid__third__line.html", null ],
    [ "err_invalid_tolerance", "classerr__invalid__tolerance.html", null ],
    [ "err_invalid_x_vector", "classerr__invalid__x__vector.html", null ],
    [ "err_less_than_5_lines", "classerr__less__than__5__lines.html", null ],
    [ "err_missing_equal_sign", "classerr__missing__equal__sign.html", null ],
    [ "err_more_than_5_lines", "classerr__more__than__5__lines.html", null ],
    [ "err_size_must_match", "classerr__size__must__match.html", null ],
    [ "err_unknown_algorithm", "classerr__unknown__algorithm.html", null ],
    [ "Input_Data", "class_input___data.html", "class_input___data" ],
    [ "matrix", "classmatrix.html", "classmatrix" ],
    [ "Polynomial", "class_polynomial.html", "class_polynomial" ],
    [ "Result_Handling", "class_result___handling.html", "class_result___handling" ]
];